name: getreferred
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_signin_button: ^1.0.0
  rxdart: ^0.24.0
  autocomplete_textfield: ^1.7.3
  dropdown_formfield: ^0.1.1
  flutter_country_picker: ^0.1.6
  flutter_typeahead: ^1.8.0
  email_validator: '^1.0.0'
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.0
  flutter_pdfview: ^1.0.1
  font_awesome_flutter: ^8.2.0
  line_icons: ^0.2.0
  firebase_storage: ^3.1.5
  line_awesome_icons: ^1.0.4+2
  image_picker: ^0.5.3+1
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.13.4+2
  carousel_slider: ^1.4.1
  flutter_tags: "^0.4.8"
  firebase_analytics: ^5.0.2
  flutter_multiselect: ^0.4.0
  quill_delta: ^1.0.1
  flutter_markdown: ^0.3.4
  image_cropper: ^1.2.1
  progress_hud: ^1.1.0
  flutter_cache_manager: ^1.2.2
  file_picker: ^1.6.2
  zefyr: ^0.10.0
  flutter_secure_storage: ^3.3.2
  cached_network_image: ^2.0.0
  enum_to_string: ^1.0.9
  intl: ^0.16.1
  provider: ^4.0.4
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/image_01.png
    - assets/images/logo.png
    - assets/images/logo.jpg
    - assets/images/profile.png
    - assets/images/google-logo.png
    - assets/images/banner.jpg
    - assets/CITI.PDF

  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: SpaceGrotesk-Regular
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.otf
    - family: AndersonGrotesk
      fonts:
        - asset: assets/fonts/AndersonGrotesk.otf
    - family: LearningCurve
      fonts:
        - asset: assets/fonts/LearningCurve.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
